/*
 * WinListDetail.java
 *
 * Created on 13. September 2005, 11:28
 */

package mp3player;

import java.awt.*;
import java.awt.event.*;
import java.util.*;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.tree.*;
import java.io.*;

/**
 *
 * @author  Sickert Alexander
 */
public class WinListDetail extends javax.swing.JFrame {
    
    public String currentFilePath;
    
    /** Creates new form WinListDetail */
    public WinListDetail() {
        initComponents();
         this.setSize(800, 500);
        this.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();

        setTitle("Details");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(710, 370));
        jPanel1.setLayout(null);

        jButton2.setLabel("Delete from Playlist");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(170, 20, 530, 30);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 690, 300);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 20, 150, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 20, 710, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        String contentToDelete;
        String content;
        String contentNew;
        int firstPart;
        int lastPart;
        UtilFunc util = new UtilFunc();

        Object o = this.jList1.getSelectedValue();
        //currFiles =  myUtil.getcontentList(config.getValue("PathToPlayList") + o.toString());  
        contentToDelete = o.toString();
        System.out.println("String to delete: " + contentToDelete);
        System.out.println("current path: " + currentFilePath);

        content = util.getFileContent(currentFilePath);
        //content = content.replaceFirst(contentToDelete, "");
        
        firstPart = content.indexOf(contentToDelete);
        lastPart = firstPart + contentToDelete.length();
        
        contentNew = content.substring(0,firstPart) + content.substring(lastPart,content.length());
        System.out.println("new Content: " + contentNew);
        util.setFileContent(currentFilePath, contentNew);
        this.fillList(currentFilePath);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    public void fillList(String filename){
        
        currentFilePath = filename;
        
        UtilFunc myUtil = new UtilFunc();
        System.out.println(filename);
        //myUtil.AddPlaylistToTask(CurrentPlaylistFile);                

        ArrayList currFiles;
        currFiles = new ArrayList();                

        currFiles =  myUtil.getcontentList(filename);                 
        this.jList1.setListData(currFiles.toArray()); 
    }
}
